spring:
  application:
    name: 'komi.vyltrorjas'
    domain: 'general'

api:
  neurotolge:
    host: https://api.tartunlp.ai/translation/

rss:
  euronews:
    uri: https://www.euronews.com/rss

telegram:
  bot:
    token: 'NOT_A_TOKEN'